### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by felipecrs**
Thank you very much for your project. It is of great help to me.

Just wanted to contribute back some realizations I had when I was trying this custom component for the first time.

I may seem silly, but I honestly thought the `factory_reset` would in fact reset the ESPHome device to factory settings for some reason. More clarification is never a bad thing, I'd say.

### CODE REVIEW

**Comment by felipecrs** [comment]
I cannot confirm this theory, but I believe the DL-F ones may be the ones which have Wi-Fi built-in like mine:

image

**Comment by syssi** [comment]
Do you like to extend the list of supported devices by your model?

**Comment by felipecrs** [comment]
It's this one:

https://aliexpress.com/item/1005007159871684.html

It's printed 8S24V100A in its shell, which I honestly don't know if it's the model number. It seems generic enough to be shared by other BMSes. But I know it's K Series.

And the docs already say:

_Daly Smart BMS K Series 100A_

That's why I just extended this line to mention my Bluetooth advertisement name.

**Comment by felipecrs** [comment]
What do you think? Feel free to patch this PR if you want.

**Comment by syssi** [comment]
I wasn't aware of the fact your series is already mentioned as supported. I expected a different series.

**Pull request merged**
