### PR TITLE
Introduce switch and button entities

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Comment by felipecrs** [comment]
What _reset_current_ does?

**Comment by felipecrs** [comment]
Found it in the xls manual, it basically resets the BMS current to zero.

I wonder what the real-life use of it would be. Do you have any idea?

I also wonder why someone would want to press `system shutdown` or maybe even `system restart`, lol. `reset` I suppose would erase the BMS settings, which could indeed be useful.

**Comment by syssi** [comment]
Just remove feature/command from your YAML if you don't want to expose the feature. I tried to replicate/make the complete command set of the BMS available. I guess reset current can be used to calibrate the current sensor.

**Comment by felipecrs** [comment]
> Just remove feature/command from your YAML if you don't want to expose the feature.

Oh yes, for sure. I was not making any point that it should be removed from the custom component.

I was just trying to learn if there was any use case I didn't think of for them, out of curiosity.

> I guess reset current can be used to calibrate the current sensor.

Thank you, that's interesting.

**Comment by felipecrs** [comment]
By the way, your custom component worked great for my Daly K Series 100A 8S through BLE. Thank you very much!

If you need help to test anything, just call me out.

**Comment by syssi** [comment]
Thanks for your feedback! I'm happy about any input! Feel free to create new issues if you miss something or if you see room for improvements.

**Pull request merged**
