### PR TITLE
Decode error bitmask

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Comment by felipecrs** [comment]
@syssi, just a reminder. Whenever you want, I can test this.

**Comment by syssi** [comment]
@felipecrs Cool! Let's move on here. I will ping you another time as soon I'm ready.

**Comment by syssi** [comment]
I'm ready. Please change your YAML configuration to this feature branch:

```
substitutions:
  external_components_source: github://syssi/esphome-daly-bms@decode-error-bitmask
```

and make sure the `error_bitmask` sensor and `errors` text sensor is already part of your configuration. Please flash the new version and check the state of the new sensors. I expect the `errors` text sensor is empty and the `error_bitmask` is `0`. If not please provide some details from your log.

**Comment by felipecrs** [comment]
Alright:

image

**Comment by syssi** [comment]
Alright. As next step please make sure there is no load on your battery (the mosfet doesn't like to switch high loads) and try to cool down one of the temperature sensors. Please record the state changes of the `error bitmask` and the values of the `errors` text sensor.

**Comment by felipecrs** [comment]
13.194.139.533.312

Internal network communication module failure;Level 2 alarm - Discharging temperature too low

**Comment by felipecrs** [comment]
After removing the sensor from the ice, everything went back to normal.

**Comment by felipecrs** [comment]
Please let me know if you'll need more testing, as I had to power my inverter off for it. Otherwise, if the battery mosfet is cut during operation, it enters in an error condition and then requires a power cycle.

**Comment by syssi** [comment]
Thanks for testing for now. I will have a look tomorrow what needs to be improved.

**Comment by syssi** [comment]
```
13194139533312 = 0b0000000000000000000011000000000000000000000000000000000000000000
                   12345678
                           12345678
                                   12345678
                                           12345678
                                                   12345678
                                                           12345678
                                                                   12345678
                                                                           12345678

                   Byte1    Byte2   Byte3   Byte4   Byte5   Byte6   Byte7   Byte8

                   pos119   pos120  pos121  pos122  pos123  pos124  pos125  pos126
                  [   Alarm1     ]  [   Alarm2   ]  [   Alarm3   ]  [   Alarm4   ]
```

**Comment by syssi** [comment]
In just realized it's not possible to publish 64bit integers in ESPHome.

**Comment by felipecrs** [comment]
If you can still parse, then maybe just remove the bitmask entity. :)

**Comment by syssi** [comment]
The 64bit alarm bitmask gets printed to the log now: https://github.com/syssi/esphome-daly-bms/pull/20/commits/85d3c7e33c035879a17eccc881012093073a59ac

Could you reflash the ESP and repeat the experiment? Thanks in advance!

**Comment by felipecrs** [comment]
Oh, or maybe you can convert it to a string/text sensor entity instead.

**Comment by felipecrs** [comment]
> Could you reflash the ESP and repeat the experiment and tell me the value from the log? Thanks in advance!

lol. I used all my ice. If you don't mind, I will do it again tomorrow.

**Comment by syssi** [comment]
Take your time! A raw frame of the BMS indicating an alarm would be helpful too.

**Comment by syssi** [comment]
This feature is ready. :-)

**Comment by felipecrs** [comment]
I captured all the logs as you requested.

[logs.txt](https://github.com/user-attachments/files/18222539/logs.txt)

Too many lines, but you can search for `'BMS Errors':` and it should make it easier to navigate.

**Comment by syssi** [comment]
These are the most important frames from the log:

```
# complete frame

D2.03.7C.0D.31.0D.33.0D.33.0D.31.0D.03.0D.31.0D.34.0D.39.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.42.00.31.00.FF.00.FF.00.FF.00.FF.00.FF.00.FF.01.0D.75.30.03.E0.0D.39.0D.03.00.42.00.31.00.00.03.E0.00.08.00.02.00.0D.00.00.00.01.00.01.0D.32.00.36.00.00.00.00.08.00.00.00.00.00.32.C7
D2.03.7C.0D.2F.0D.30.0D.31.0D.30.0D.01.0D.30.0D.31.0D.37.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.42.00.2A.00.FF.00.FF.00.FF.00.FF.00.FF.00.FF.01.0D.75.30.03.E0.0D.37.0D.01.00.42.00.2A.00.00.03.E0.00.08.00.02.00.0D.00.00.00.01.00.01.0D.30.00.36.00.00.00.00.0C.00.00.00.00.00.ED.D6
D2.03.7C.0D.2F.0D.30.0D.30.0D.2F.0D.01.0D.30.0D.30.0D.36.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.42.00.3B.00.FF.00.FF.00.FF.00.FF.00.FF.00.FF.01.0D.75.30.03.E0.0D.36.0D.01.00.42.00.3B.00.00.03.E0.00.08.00.02.00.0D.00.00.00.01.00.01.0D.2F.00.35.00.00.00.00.04.00.00.00.00.00.3C.FA

# tail (alarms + crc)
00.00.08.00.00.00.00.00. 32.C7
00.00.0C.00.00.00.00.00. ED.D6   # 13194139533312, 'Warning: Temperature difference too high;Critical: Temperature difference too high'
00.00.04.00.00.00.00.00. 3C.FA  # 4398046511104, 'Warning: Temperature difference too high'
```

**Comment by felipecrs** [comment]
Awesome! Thanks a lot!

**Pull request merged**
